# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Snappy/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(566, 794)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/radioMapIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.application_tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.application_tabs.setObjectName("application_tabs")
        self.snap_na = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 221, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 238, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 221, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 238, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 221, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 238, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 221, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 238, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 221, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 238, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 110, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 221, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 221, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 221, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.snap_na.setPalette(palette)
        self.snap_na.setObjectName("snap_na")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.snap_na)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.snap_na)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -35, 528, 780))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.snap_na_run = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.snap_na_run.setObjectName("snap_na_run")
        self.gridLayout_3.addWidget(self.snap_na_run, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.snap_na_plot_region = QtWidgets.QComboBox(self.groupBox_3)
        self.snap_na_plot_region.setObjectName("snap_na_plot_region")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.snap_na_plot_region)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.snap_na_bdiana_version = QtWidgets.QLineEdit(self.groupBox_3)
        self.snap_na_bdiana_version.setObjectName("snap_na_bdiana_version")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.snap_na_bdiana_version)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.snap_na_duration = QtWidgets.QLineEdit(self.groupBox)
        self.snap_na_duration.setObjectName("snap_na_duration")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.snap_na_duration)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.snap_na_run_length = QtWidgets.QLineEdit(self.groupBox)
        self.snap_na_run_length.setObjectName("snap_na_run_length")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.snap_na_run_length)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.snap_na_location = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snap_na_location.sizePolicy().hasHeightForWidth())
        self.snap_na_location.setSizePolicy(sizePolicy)
        self.snap_na_location.setObjectName("snap_na_location")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.snap_na_location)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.snap_na_latitude = QtWidgets.QLineEdit(self.groupBox)
        self.snap_na_latitude.setEnabled(False)
        self.snap_na_latitude.setObjectName("snap_na_latitude")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.snap_na_latitude)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.snap_na_longitude = QtWidgets.QLineEdit(self.groupBox)
        self.snap_na_longitude.setEnabled(False)
        self.snap_na_longitude.setObjectName("snap_na_longitude")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.snap_na_longitude)
        self.snap_na_show_advanced = QtWidgets.QCheckBox(self.groupBox)
        self.snap_na_show_advanced.setObjectName("snap_na_show_advanced")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.snap_na_show_advanced)
        self.snap_na_start_time = QtWidgets.QDateTimeEdit(self.groupBox)
        self.snap_na_start_time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.snap_na_start_time.setDisplayFormat("yyyy-MM-dd HH:mm UTC")
        self.snap_na_start_time.setCurrentSectionIndex(3)
        self.snap_na_start_time.setTimeSpec(QtCore.Qt.UTC)
        self.snap_na_start_time.setObjectName("snap_na_start_time")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.snap_na_start_time)
        self.verticalLayout.addLayout(self.formLayout)
        self.snap_na_advanced_settings = QtWidgets.QGroupBox(self.groupBox)
        self.snap_na_advanced_settings.setChecked(False)
        self.snap_na_advanced_settings.setObjectName("snap_na_advanced_settings")
        self.formLayout_2 = QtWidgets.QFormLayout(self.snap_na_advanced_settings)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.snap_na_advanced_settings)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.snap_na_met_model = QtWidgets.QComboBox(self.snap_na_advanced_settings)
        self.snap_na_met_model.setObjectName("snap_na_met_model")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.snap_na_met_model)
        self.label_30 = QtWidgets.QLabel(self.snap_na_advanced_settings)
        self.label_30.setObjectName("label_30")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.snap_na_met_ec_runtime = QtWidgets.QComboBox(self.snap_na_advanced_settings)
        self.snap_na_met_ec_runtime.setObjectName("snap_na_met_ec_runtime")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.snap_na_met_ec_runtime)
        self.snap_na_release_bomb = QtWidgets.QGroupBox(self.snap_na_advanced_settings)
        self.snap_na_release_bomb.setCheckable(True)
        self.snap_na_release_bomb.setChecked(False)
        self.snap_na_release_bomb.setObjectName("snap_na_release_bomb")
        self.formLayout_6 = QtWidgets.QFormLayout(self.snap_na_release_bomb)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_29 = QtWidgets.QLabel(self.snap_na_release_bomb)
        self.label_29.setObjectName("label_29")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.snap_na_bomb_yield = QtWidgets.QComboBox(self.snap_na_release_bomb)
        self.snap_na_bomb_yield.setObjectName("snap_na_bomb_yield")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.snap_na_bomb_yield)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.snap_na_release_bomb)
        self.snap_na_release_npp = QtWidgets.QGroupBox(self.snap_na_advanced_settings)
        self.snap_na_release_npp.setCheckable(True)
        self.snap_na_release_npp.setObjectName("snap_na_release_npp")
        self.formLayout_8 = QtWidgets.QFormLayout(self.snap_na_release_npp)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_4 = QtWidgets.QLabel(self.snap_na_release_npp)
        self.label_4.setObjectName("label_4")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.snap_na_bottom = QtWidgets.QLineEdit(self.snap_na_release_npp)
        self.snap_na_bottom.setObjectName("snap_na_bottom")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.snap_na_bottom)
        self.label_5 = QtWidgets.QLabel(self.snap_na_release_npp)
        self.label_5.setObjectName("label_5")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.snap_na_top = QtWidgets.QLineEdit(self.snap_na_release_npp)
        self.snap_na_top.setObjectName("snap_na_top")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.snap_na_top)
        self.label_6 = QtWidgets.QLabel(self.snap_na_release_npp)
        self.label_6.setObjectName("label_6")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.snap_na_radius = QtWidgets.QLineEdit(self.snap_na_release_npp)
        self.snap_na_radius.setObjectName("snap_na_radius")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.snap_na_radius)
        self.label_7 = QtWidgets.QLabel(self.snap_na_release_npp)
        self.label_7.setObjectName("label_7")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.snap_na_cs137 = QtWidgets.QLineEdit(self.snap_na_release_npp)
        self.snap_na_cs137.setObjectName("snap_na_cs137")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.snap_na_cs137)
        self.label_8 = QtWidgets.QLabel(self.snap_na_release_npp)
        self.label_8.setObjectName("label_8")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.snap_na_xe133 = QtWidgets.QLineEdit(self.snap_na_release_npp)
        self.snap_na_xe133.setObjectName("snap_na_xe133")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.snap_na_xe133)
        self.label_9 = QtWidgets.QLabel(self.snap_na_release_npp)
        self.label_9.setObjectName("label_9")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.snap_na_i131 = QtWidgets.QLineEdit(self.snap_na_release_npp)
        self.snap_na_i131.setObjectName("snap_na_i131")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.snap_na_i131)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.snap_na_release_npp)
        self.verticalLayout.addWidget(self.snap_na_advanced_settings)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.application_tabs.addTab(self.snap_na, "")
        self.snap_backtrack = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 235, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 117, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 157, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 235, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 235, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 117, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 157, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 235, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 117, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 235, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 245, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 117, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 157, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 117, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 117, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 235, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 235, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 235, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.snap_backtrack.setPalette(palette)
        self.snap_backtrack.setObjectName("snap_backtrack")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.snap_backtrack)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.snap_backtrack)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 542, 745))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.snap_bt_output_dir = QtWidgets.QLineEdit(self.groupBox_4)
        self.snap_bt_output_dir.setObjectName("snap_bt_output_dir")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.snap_bt_output_dir)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.snap_bt_run_length = QtWidgets.QLineEdit(self.groupBox_4)
        self.snap_bt_run_length.setObjectName("snap_bt_run_length")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.snap_bt_run_length)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.snap_bt_measurements = QtWidgets.QTableWidget(self.groupBox_5)
        self.snap_bt_measurements.setAlternatingRowColors(True)
        self.snap_bt_measurements.setObjectName("snap_bt_measurements")
        self.snap_bt_measurements.setColumnCount(0)
        self.snap_bt_measurements.setRowCount(0)
        self.gridLayout_2.addWidget(self.snap_bt_measurements, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.snap_bt_met_input = QtWidgets.QLineEdit(self.groupBox_6)
        self.snap_bt_met_input.setObjectName("snap_bt_met_input")
        self.verticalLayout_4.addWidget(self.snap_bt_met_input)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.snap_bt_run = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.snap_bt_run.setObjectName("snap_bt_run")
        self.verticalLayout_6.addWidget(self.snap_bt_run)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.application_tabs.addTab(self.snap_backtrack, "")
        self.eemep_ash_cloud = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 247, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(104, 119, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 159, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 247, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 247, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(104, 119, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 159, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 247, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(104, 119, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 247, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(104, 119, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 159, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(104, 119, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(104, 119, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(209, 239, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.eemep_ash_cloud.setPalette(palette)
        self.eemep_ash_cloud.setObjectName("eemep_ash_cloud")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.eemep_ash_cloud)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.eemep_ash_cloud)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 542, 745))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.eemep_start_time = QtWidgets.QLineEdit(self.groupBox_7)
        self.eemep_start_time.setObjectName("eemep_start_time")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.eemep_start_time)
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.eemep_ash_cloud_height = QtWidgets.QLineEdit(self.groupBox_7)
        self.eemep_ash_cloud_height.setObjectName("eemep_ash_cloud_height")
        self.horizontalLayout_5.addWidget(self.eemep_ash_cloud_height)
        self.eemep_ash_cloud_datum = QtWidgets.QComboBox(self.groupBox_7)
        self.eemep_ash_cloud_datum.setObjectName("eemep_ash_cloud_datum")
        self.horizontalLayout_5.addWidget(self.eemep_ash_cloud_datum)
        self.eemep_ash_cloud_height_unknown = QtWidgets.QCheckBox(self.groupBox_7)
        self.eemep_ash_cloud_height_unknown.setObjectName("eemep_ash_cloud_height_unknown")
        self.horizontalLayout_5.addWidget(self.eemep_ash_cloud_height_unknown)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.eemep_run_length = QtWidgets.QLineEdit(self.groupBox_7)
        self.eemep_run_length.setObjectName("eemep_run_length")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.eemep_run_length)
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.eemep_location = QtWidgets.QComboBox(self.groupBox_7)
        self.eemep_location.setObjectName("eemep_location")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eemep_location)
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.eemep_latitude = QtWidgets.QLineEdit(self.groupBox_7)
        self.eemep_latitude.setObjectName("eemep_latitude")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.eemep_latitude)
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.eemep_longitude = QtWidgets.QLineEdit(self.groupBox_7)
        self.eemep_longitude.setObjectName("eemep_longitude")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.eemep_longitude)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_7.setObjectName("formLayout_7")
        self.eemep_continue_last_run = QtWidgets.QCheckBox(self.groupBox_8)
        self.eemep_continue_last_run.setObjectName("eemep_continue_last_run")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.eemep_continue_last_run)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setObjectName("label_25")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.eemep_volcano_type = QtWidgets.QComboBox(self.groupBox_8)
        self.eemep_volcano_type.setObjectName("eemep_volcano_type")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.eemep_volcano_type)
        self.label_31 = QtWidgets.QLabel(self.groupBox_8)
        self.label_31.setObjectName("label_31")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.eemep_met_model = QtWidgets.QComboBox(self.groupBox_8)
        self.eemep_met_model.setObjectName("eemep_met_model")
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.eemep_met_model)
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setObjectName("label_27")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.eemep_ec_model_run_time = QtWidgets.QComboBox(self.groupBox_8)
        self.eemep_ec_model_run_time.setObjectName("eemep_ec_model_run_time")
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.eemep_ec_model_run_time)
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.groupBox_8)
        self.eemep_volcano_altitude = QtWidgets.QLineEdit(self.groupBox_7)
        self.eemep_volcano_altitude.setObjectName("eemep_volcano_altitude")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.eemep_volcano_altitude)
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.verticalLayout_8.addWidget(self.groupBox_7)
        self.eemep_run = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.eemep_run.setObjectName("eemep_run")
        self.verticalLayout_8.addWidget(self.eemep_run)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.addWidget(self.scrollArea_3)
        self.application_tabs.addTab(self.eemep_ash_cloud, "")
        self.gridLayout.addWidget(self.application_tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_14.setBuddy(self.snap_na_plot_region)
        self.label_15.setBuddy(self.snap_na_bdiana_version)
        self.label.setBuddy(self.snap_na_start_time)
        self.label_2.setBuddy(self.snap_na_duration)
        self.label_3.setBuddy(self.snap_na_run_length)
        self.label_11.setBuddy(self.snap_na_location)
        self.label_12.setBuddy(self.snap_na_latitude)
        self.label_13.setBuddy(self.snap_na_longitude)
        self.label_10.setBuddy(self.snap_na_met_model)
        self.label_29.setBuddy(self.snap_na_bomb_yield)
        self.label_4.setBuddy(self.snap_na_bottom)
        self.label_5.setBuddy(self.snap_na_top)
        self.label_6.setBuddy(self.snap_na_radius)
        self.label_7.setBuddy(self.snap_na_cs137)
        self.label_8.setBuddy(self.snap_na_xe133)
        self.label_9.setBuddy(self.snap_na_i131)

        self.retranslateUi(MainWindow)
        self.application_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.snap_na_duration, self.snap_na_run_length)
        MainWindow.setTabOrder(self.snap_na_run_length, self.snap_na_location)
        MainWindow.setTabOrder(self.snap_na_location, self.snap_na_latitude)
        MainWindow.setTabOrder(self.snap_na_latitude, self.snap_na_longitude)
        MainWindow.setTabOrder(self.snap_na_longitude, self.snap_na_plot_region)
        MainWindow.setTabOrder(self.snap_na_plot_region, self.snap_na_bdiana_version)
        MainWindow.setTabOrder(self.snap_na_bdiana_version, self.snap_na_run)
        MainWindow.setTabOrder(self.snap_na_run, self.application_tabs)
        MainWindow.setTabOrder(self.application_tabs, self.snap_bt_output_dir)
        MainWindow.setTabOrder(self.snap_bt_output_dir, self.snap_bt_run_length)
        MainWindow.setTabOrder(self.snap_bt_run_length, self.snap_bt_measurements)
        MainWindow.setTabOrder(self.snap_bt_measurements, self.snap_bt_met_input)
        MainWindow.setTabOrder(self.snap_bt_met_input, self.snap_bt_run)
        MainWindow.setTabOrder(self.snap_bt_run, self.eemep_start_time)
        MainWindow.setTabOrder(self.eemep_start_time, self.eemep_ash_cloud_height)
        MainWindow.setTabOrder(self.eemep_ash_cloud_height, self.eemep_ash_cloud_datum)
        MainWindow.setTabOrder(self.eemep_ash_cloud_datum, self.eemep_ash_cloud_height_unknown)
        MainWindow.setTabOrder(self.eemep_ash_cloud_height_unknown, self.eemep_run_length)
        MainWindow.setTabOrder(self.eemep_run_length, self.eemep_location)
        MainWindow.setTabOrder(self.eemep_location, self.eemep_latitude)
        MainWindow.setTabOrder(self.eemep_latitude, self.eemep_longitude)
        MainWindow.setTabOrder(self.eemep_longitude, self.eemep_volcano_altitude)
        MainWindow.setTabOrder(self.eemep_volcano_altitude, self.eemep_continue_last_run)
        MainWindow.setTabOrder(self.eemep_continue_last_run, self.eemep_volcano_type)
        MainWindow.setTabOrder(self.eemep_volcano_type, self.eemep_met_model)
        MainWindow.setTabOrder(self.eemep_met_model, self.eemep_ec_model_run_time)
        MainWindow.setTabOrder(self.eemep_ec_model_run_time, self.eemep_run)
        MainWindow.setTabOrder(self.eemep_run, self.scrollArea_3)
        MainWindow.setTabOrder(self.scrollArea_3, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.scrollArea_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SnapPyGui"))
        self.snap_na_run.setText(_translate("MainWindow", "Run SNAP nuclear"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Mail / plots / Diana"))
        self.label_14.setText(_translate("MainWindow", "Plot region"))
        self.label_15.setText(_translate("MainWindow", "BDiana version (e.g., 3.39)"))
        self.groupBox.setTitle(_translate("MainWindow", "Nuclear source term"))
        self.label.setText(_translate("MainWindow", "UTC start time (YYYY-MM-DD HH:MM)"))
        self.label_2.setText(_translate("MainWindow", "Release duration (hours)"))
        self.label_3.setText(_translate("MainWindow", "Run length (hours)"))
        self.label_11.setText(_translate("MainWindow", "Location / nuclear power plant"))
        self.label_12.setText(_translate("MainWindow", "Latitude (DD:HH:MM / DD°HH\'MM\")"))
        self.label_13.setText(_translate("MainWindow", "Longitude (DD:HH:MM / DD°HH\'MM\")"))
        self.snap_na_show_advanced.setText(_translate("MainWindow", "Show advanced settings"))
        self.snap_na_advanced_settings.setTitle(_translate("MainWindow", "Advanced"))
        self.label_10.setText(_translate("MainWindow", "Met model:"))
        self.label_30.setText(_translate("MainWindow", "EC model runtime"))
        self.snap_na_release_bomb.setTitle(_translate("MainWindow", "Nuclear bomb"))
        self.label_29.setText(_translate("MainWindow", "Explosive yield"))
        self.snap_na_release_npp.setTitle(_translate("MainWindow", "Nuclear power plant"))
        self.label_4.setText(_translate("MainWindow", "Release bottom (meters above ground)"))
        self.label_5.setText(_translate("MainWindow", "Release top (meters above ground)"))
        self.label_6.setText(_translate("MainWindow", "Release radius (meters)"))
        self.label_7.setText(_translate("MainWindow", "Cs-137 release (Bq / s)"))
        self.label_8.setText(_translate("MainWindow", "Xe-133 release (Bq / s)"))
        self.label_9.setText(_translate("MainWindow", "I-131 release (Bq / s)"))
        self.application_tabs.setTabText(self.application_tabs.indexOf(self.snap_na), _translate("MainWindow", "SNAP Nuclear Accident"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Case setup"))
        self.label_16.setText(_translate("MainWindow", "Output directory"))
        self.label_17.setText(_translate("MainWindow", "Run length"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Measurements"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Special meteorology input"))
        self.label_18.setText(_translate("MainWindow", "optional, e.g.\n"
"/lustre/storeB/project/fou/kl/cerad/Projects/2017_Ephsogam/EC_MET/NRPA_EUROPE_0_1_{UTC:02d}/meteo{year:04d}{month:02d}{day:02d}_{dayoffset:02d}.nc"))
        self.snap_bt_run.setText(_translate("MainWindow", "Run SNAP backtrack"))
        self.application_tabs.setTabText(self.application_tabs.indexOf(self.snap_backtrack), _translate("MainWindow", "SNAP Backtracking"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Ash source term"))
        self.label_19.setText(_translate("MainWindow", "UTC start time (YYYY-MM-DD HH:MM)"))
        self.label_20.setText(_translate("MainWindow", "Ash cloud height"))
        self.eemep_ash_cloud_height_unknown.setText(_translate("MainWindow", "Unknown"))
        self.label_21.setText(_translate("MainWindow", "Run length (hours)"))
        self.label_22.setText(_translate("MainWindow", "Location / volcano"))
        self.label_23.setText(_translate("MainWindow", "Latitude"))
        self.label_24.setText(_translate("MainWindow", "Longitude"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Advanced"))
        self.eemep_continue_last_run.setText(_translate("MainWindow", "Continue previous run"))
        self.label_25.setText(_translate("MainWindow", "Volcano type"))
        self.label_31.setText(_translate("MainWindow", "Met model:"))
        self.label_27.setText(_translate("MainWindow", "EC model run time"))
        self.label_26.setText(_translate("MainWindow", "Volcano altitude"))
        self.eemep_run.setText(_translate("MainWindow", "Run EEMEP ash cloud"))
        self.application_tabs.setTabText(self.application_tabs.indexOf(self.eemep_ash_cloud), _translate("MainWindow", "EEMEP Ash Cloud"))
